version: '3.5'

services:
  esport_mysql:
    image: mysql:8
    command: mysqld --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: esport_mysql_container
    user: root
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=esportle
