org: reubenl
service: lolesportle

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-1
  environment:
    DB_HOST: ${self:custom.envpath.DB_HOST}
    DB_PORT: ${self:custom.envpath.DB_PORT}
    DB_USER: ${self:custom.envpath.DB_USER}
    DB_PASSWORD: ${self:custom.envpath.DB_PASSWORD}

custom:
  envpath: "${file(./.env.yml):${opt:stage, self:provider.stage}}"

functions:
  findTournaments:
    handler: handlers/findTournaments.handler

  scrapeTournaments:
    handler: handlers/scrapeTournaments.handler

  scrapeTeams:
    handler: handlers/scrapeTeams.handler
